### ISSUE TITLE
[Bug]: Config Issues

### ISSUE THREAD

**Issue by mihcox** [Kometa-Team/Quickstart#677]
### Version Number

.86

### What branch are you on?

master

### Describe the Bug

I built this using only the gui, but got an error that it did not pass validation, here's the output:

'content_rating' is not one of ['aspect', 'audio_codec', 'commonsense', 'content_rating_au', 'content_rating_de', 'content_rating_nz', 'content_rating_uk', 'content_rating_us_movie', 'content_rating_us_show', 'direct_play', 'episode_info', 'language_count', 'flixpatrol', 'languages', 'mediastinger', 'network', 'ratings', 'resolution', 'ribbon', 'runtimes', 'status', 'streaming', 'studio', 'versions', 'video_format']

Failed validating 'enum' in schema[1]['properties']['default']:
    {'type': 'string',
     'enum': ['aspect',
              'audio_codec',
              'commonsense',
              'content_rating_au',
              'content_rating_de',
              'content_rating_nz',
              'content_rating_uk',
              'content_rating_us_movie',
              'content_rating_us_show',
              'direct_play',
              'episode_info',
              'language_count',
              'flixpatrol',
              'languages',
              'mediastinger',
              'network',
              'ratings',
              'resolution',
              'ribbon',
              'runtimes',
              'status',
              'streaming',
              'studio',
              'versions',
              'video_format']}

On instance['default']:
    'content_rating'

**Comment by mihcox** [comment]
![Image](https://github.com/user-attachments/assets/d970cec5-e747-475e-841a-05d6e41faa2d)

I am not using the content selections that I can tell for this to be an issue

**Comment by mihcox** [comment]
slightly more info, if i add any type of content rating to my overlays, the issue is no longer there. Seems there's an issue if you do NOT select a content rating overlay at all?

**Comment by bullmoose20** [comment]
> slightly more info, if i add any type of content rating to my overlays, the issue is no longer there. Seems there's an issue if you do NOT select a content rating overlay at all?

This was fixed in the most recent develop release.

**Comment by bullmoose20** [comment]
https://github.com/Kometa-Team/Quickstart/issues/671

**Comment by Darrenduds** [comment]
I am on  Version: 0.8.6-build2 and I still get this same issue.

**Comment by bullmoose20** [comment]
> I am on  Version: 0.8.6-build2 and get this same issue. Which build number is it fixed on?

It's been fixed since the build referenced in #671

There must be another edge case that I did not test for?

I have tried a fresh config, not selecting any content rating overlays went to final page... no issues 

Then I selected some, moved to final page.... no issues

Then I went back and unselected all of them to eliminate content_rating overlays, went back to final page.... no issues

**Comment by bullmoose20** [comment]
Ok. I was able to reproduce the issue. Time to figure out why this issue came back.

**Comment by bullmoose20** [comment]
So the issue was we had fixed it for Movies and not for Shows...

**Comment by bullmoose20** [comment]
Actually, I am pretty sure the fix was pushed last night. Would be nice if someone else could confirm...
